language: python
python:
- '3.6'
addons:
  ssh_known_hosts:
  - 123.45.56.78
branches:
  only:
  - master
env:
  global:
  - REMOTE_APP_DIR=/var/www/MY_DOMAIN.COM/
  - REMOTE_USER=deploy
  - REMOTE_HOST=123.45.56.78
  - PORT=8080
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
before_install:
- openssl aes-256-cbc -K $encrypted_8dc034ad8bd9_key -iv $encrypted_8dc034ad8bd9_iv
  -in deploy_rsa_2018-02-02.enc -out deploy_rsa_2018-02-02 -d
