language: python
python:
- '3.6'
addons:
  ssh_known_hosts:
  - 178.62.27.235
branches:
  only:
  - master
env:
  global:
  - REMOTE_APP_DIR=/var/www/
  - REMOTE_USER=deploy
  - REMOTE_HOST=178.62.27.235
  - REMOTE_SSH_PORT=2221
  - PORT=8080
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
before_deploy:
- openssl aes-256-cbc -K $encrypted_369c79041528_key -iv $encrypted_369c79041528_iv
  -in deploy_rsa_2018-02-02.enc -out /tmp/deploy_rsa_2018-02-02 -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa_2018-02-02
- ssh-add /tmp/deploy_rsa_2018-02-02

# Adding unknown host to ~/.ssh/known_hosts file in case we're connecting for the first time.
# See: https://medium.com/@wblankenship/bash-automatically-populating-a-known-hosts-file-15ea28d06c02
# Slightly modified.
- ! eval "ssh-keygen -F $REMOTE_HOST 2>/dev/null 1>/dev/null" && ssh-keyscan -t rsa -T 10 $REMOTE_HOST >> ~/.ssh/known_hosts; # Ignoring non-zero return value

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet -e "ssh -p $REMOTE_SSH_PORT" $TRAVIS_BUILD_DIR/growing_commander_server $REMOTE_USER@$REMOTE_HOST:$REMOTE_APP_DIR
  on:
    branch: master