language: python
python:
- '3.6'
addons:
  ssh_known_hosts:
  - 178.62.27.235
branches:
  only:
  - master
env:
  global:
  - REMOTE_APP_DIR=test/growing-commander-server
  - REMOTE_USER=deploy
  - REMOTE_HOST=178.62.27.235
  - PORT=8080
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
before_install:
- openssl aes-256-cbc -K $encrypted_369c79041528_key -iv $encrypted_369c79041528_iv
  -in deploy_rsa_2018-02-02.enc -out deploy_rsa_2018-02-02 -d